# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ee692b3a8413e1b1b60ca67a6ecf0347"
application_url = "https://example.com"
embedded = true
name = "b2b-cart-approval"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_draft_orders"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://PLACEHOLDER_NGROK_URL"
subpath = "b2b-approval"
prefix = "apps"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
